apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: rewrite-app-with-istio
build:
  artifacts:
    - image: rewrite-app-with-istio
    - image: rewrite-app-with-istio-v2
      context: ./v2/
deploy:
  helm:
    releases:
      - name: rewrite-app-with-istio
        chartPath: helm
        artifactOverrides:
          deployments:
            blue:
              image: rewrite-app-with-istio
            green:
              image: rewrite-app-with-istio-v2
        imageStrategy:
          helm: {}

