{{- if .Values.istioGateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.istioGateway.selector | nindent 4 }}
  servers:
    {{- toYaml .Values.istioGateway.servers | nindent 4 }}
{{- end }}