{{- range $virtualService := .Values.istioVirtualServices }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $virtualService.name }}
  labels:
    {{- include "..labels" $ | nindent 4 }}
spec:
  {{- if $virtualService.gateways }}
  gateways:
    {{- toYaml $virtualService.gateways | nindent 4 }}
  {{- end }}
  hosts:
    {{- toYaml $virtualService.hosts | nindent 4 }}
  http:
    {{- toYaml $virtualService.routes | nindent 4 }}
{{- end }}
