# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployments:
  blue:
    replicaCount: 1
    image:
      repository: rewrite-app-with-istio
      pullPolicy: IfNotPresent
      tag: latest
    containerPort: "5000"
    podLabels:
      sidecar.istio.io/inject: "true"
      color: blue
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    env:
      EXAMPLE_SERVICE: http://rewrite-app-with-istio
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
  green:
    replicaCount: 1
    image:
      repository: rewrite-app-with-istio-v2
      pullPolicy: IfNotPresent
      tag: latest
    containerPort: "5000"
    podLabels:
      sidecar.istio.io/inject: "true"
      color: green
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    env:
      EXAMPLE_SERVICE: http://rewrite-app-with-istio
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 80

istioGateway:
  enabled: true
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - rewrite-app-with-istio.test

istioVirtualServices:
  - name: ingress
    gateways:
      - rewrite-app-with-istio
    hosts:
      - rewrite-app-with-istio.test
    routes:
      - name: "rewrite-app-with-istio-route-v2"
        match:
          - uri:
              prefix: "/random/number"
        route:
          - destination:
              host: rewrite-app-with-istio
              subset: green
            weight: 0
          - destination:
              host: rewrite-app-with-istio
              subset: blue
            weight: 100
      - name: "rewrite-app-with-istio-route-v1"
        route:
          - destination:
              host: rewrite-app-with-istio
              subset: blue
            weight: 100
  - name: cluster
    hosts:
      - rewrite-app-with-istio
    routes:
      - name: "rewrite-app-with-istio-route-v2"
        match:
          - uri:
              prefix: "/random/number"
        route:
          - destination:
              host: rewrite-app-with-istio
              subset: green
            weight: 0
          - destination:
              host: rewrite-app-with-istio
              subset: blue
            weight: 100
      - name: "rewrite-app-with-istio-route-v1"
        route:
          - destination:
              host: rewrite-app-with-istio
              subset: blue
            weight: 100
